{
   "kind": "pipeline",
   "name": "Windows (amd64)",
   "platform": {
      "arch": "amd64"
   },
   "steps": [
      {
         "commands": [
            "git fetch --tags",
            "git submodule update --init --recursive --depth=1 --jobs=4"
         ],
         "image": "drone/git",
         "name": "submodules"
      },
      {
         "commands": [
            "echo \"Building on ${DRONE_STAGE_MACHINE}\"",
            "echo \"man-db man-db/auto-update boolean false\" | debconf-set-selections",
            "apt-get -o=Dpkg::Use-Pty=0 -q update",
            "apt-get -o=Dpkg::Use-Pty=0 -q install -y eatmydata",
            "eatmydata apt-get -o=Dpkg::Use-Pty=0 -q install --no-install-recommends -y build-essential cmake git pkg-config ccache g++-mingw-w64-x86-64-posix nsis zip icoutils automake libtool librsvg2-bin bison",
            "update-alternatives --set x86_64-w64-mingw32-gcc /usr/bin/x86_64-w64-mingw32-gcc-posix",
            "update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix",
            #"JOBS=6 VERBOSE=1 ./contrib/windows.sh -DSTRIP_SYMBOLS=ON -DGUI_EXE=$${DRONE_WORKSPACE}/gui/release/Belnet-GUI_portable.exe -DLOCAL_MIRROR=https://oxen.rocks/deps ",
            "./contrib/ci/drone-static-upload.sh"
         ],
         "environment": {
            "SSH_KEY": {
               "from_secret": "SSH_KEY"
            },
            "WINDOWS_BUILD_NAME": "x64"
         },
         "image": "debian:bookworm",
         "name": "build",
         "pull": "always"
      }
   ],
   "trigger": {
      "branch": {
         "exclude": [
            "debian/*",
            "ubuntu/*"
         ]
      }
   },
   "type": "docker"
}
